version: 2.1

params: &filters 
  filters:
    tags:
      only: /.*/
    branches:
      only: /^(main)$/

jobs:
  build:
    executor: node
    steps:
      - checkout 
  deploy:
    executor: node
    steps:
      - checkout
      - run: npm set //registry.npmjs.org/:_authToken=$npm_token
      - run: git fetch --tags
      - run: npx lerna publish from-git --yes

workflows:
  main:
    jobs:
      - build:
          <<: *filters
      - deploy:
          requires: [ build ]
          <<: *filters


executors:
  node:
    docker:
      - image: cimg/node:lts
