version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0
  lerna-cache: ryanpedersen/lerna-cache@0.1.0
  
jobs:
  build:
    executor: node
    steps:
      - checkout
  test:
    executor: node 
    steps:
      - checkout
  
workflows:
  staging:
    jobs:
      - build
      - test
      - cypress/run:
          name: integration_tests
          executor: node-browsers
          post-checkout: 
            - run: sudo apt-get update && sudo apt-get install xvfb
            - lerna-cache/monorepo_cache:
                filename: combined-package-lock.txt
          start: npx lerna run start --parallel
          cache-key: v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
          wait-on: http://localhost:3000
          no-workspace: true

executors:
  node:
    docker:
      - image: cimg/node:lts
  base:
    docker:
      - image: cimg/base:stable
  node-browsers:
    docker:
      - image: cimg/node:16.17.0-browsers

# VS Code Extension Version: 1.0.0