version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0
  lerna-cache: ryanpedersen/lerna-cache@0.2.0
  
jobs:
  unit_tests:
    executor: node 
    steps:
      - checkout
      - lerna-cache/monorepo_cache:
          filename: combined-package-lock.txt
          test-commands: 
            - run:
                command: |
                  npx lerna run test
  lint:
    executor: node 
    steps:
      - checkout
      - lerna-cache/monorepo_cache:
          filename: combined-package-lock.txt
          test-commands: 
            - run: 
                name: Lint
                command: |
                  npx lerna run lint
  tag:
    executor: node
    parameters:
      semver:
        default: "patch"
        type: string
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:af:78:86:80:10:b6:f9:36:8a:29:9a:01:b7:e4:6e"
      - checkout 
      - run: | 
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_NAME
      - run: npx lerna version << parameters.semver >> --yes

workflows:
  staging:
    jobs:
      - lint
      - unit_tests:
          requires: [ lint ]
      - cypress/run:
          name: integration_tests
          executor: node-browsers
          requires: [ unit_tests ]
          post-checkout: 
            - run: sudo apt-get update && sudo apt-get install xvfb
            - lerna-cache/monorepo_cache:
                filename: combined-package-lock.txt
          start: npx lerna run start --parallel
          cache-key: v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
          wait-on: http://localhost:3000
          no-workspace: true
      - tag
executors:
  node:
    docker:
      - image: cimg/node:lts
    resource_class: medium
  base:
    docker:
      - image: cimg/base:stable
  node-browsers:
    docker:
      - image: cimg/node:16.17.0-browsers