version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0

jobs:
  build:
    executor: node
    steps:
      - checkout
  test:
    executor: node 
    steps:
      - checkout
  
workflows:
  staging:
    jobs:
      - build
      - test
      - cypress/run:
          name: integration_tests
          executor: node 
          start: npx lerna run start --parallel
          wait-on: http://localhost:3000

executors:
  node:
    docker:
      - image: cimg/node:lts
  base:
    docker:
      - image: cimg/base:stable

# VS Code Extension Version: 1.0.0