version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor: node
    parameters:
      scope:
        default: "browser-jotter"
        type: string
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npx lerna run test --scope=<< parameters.scope >>

workflows:
  docs:
    when:
      unless: [ << pipeline.parameters.cli >>, << pipeline.parameters.local-api >>, << pipeline.parameters.local-client >> ]
    jobs:
      - build
  cli:
    when: << pipeline.parameters.cli >>
    jobs:
      - build
  
  local-api:
    when: << pipeline.parameters.local-api >>
    jobs:
      - build:
          scope: "@browser-jotter/local-api"
  
  local-client:
    when: << pipeline.parameters.local-client >>
    jobs:
      - build:
          scope: "@browser-jotter/local-client"

executors:
  node:
    docker:
      - image: cimg/node:18.11.0

parameters:
  cli:
    type: boolean
    default: false
  local-api:
    type: boolean
    default: false
  local-client:
    type: boolean
    default: false

# VS Code Extension Version: 1.0.0