version: 2.1

orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

jobs:
  build:
    executor: node
    parameters:
      scope:
        default: "browser-jotter"
        type: string
    steps:
      - checkout
      - monorepo_cache:
          filename: combined-package-lock.txt
      - run:
          command: |
            npx lerna run test --scope=<< parameters.scope >>

workflows:
  cypress_testing:
    jobs:
      - cypress/run:
          name: integration_tests
          executor: node-browsers
          post-checkout: 
            - run: sudo apt-get update && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            # - run: npx lerna bootstrap --ci
            - monorepo_cache:
                filename: combined-package-lock.txt
          start: npx lerna run start --parallel
          # install-command: cat combined-package-lock.txt
          wait-on: http://localhost:3000
          no-workspace: true
  docs:
    when:
      unless: [ << pipeline.parameters.cli >>, << pipeline.parameters.local-api >>, << pipeline.parameters.local-client >> ]
    jobs:
      - build
  cli:
    when: << pipeline.parameters.cli >>
    jobs:
      - build
  
  local-api:
    when: << pipeline.parameters.local-api >>
    jobs:
      - build:
          scope: "@browser-jotter/local-api"
  
  local-client:
    when: << pipeline.parameters.local-client >>
    jobs:
      - build:
          scope: "@browser-jotter/local-client"

executors:
  node:
    docker:
      - image: cimg/node:18.11.0
  node-browsers:
    docker:
      - image: cimg/node:18.8.0-browsers

commands:
  monorepo_cache:
    description: "Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna la -a | awk -F packages '{printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > combined-package-lock.txt
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
            - v1-deps
      - run:
          name: Bootstrap
          command: npx lerna bootstrap
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
          paths:
            - node_modules
            - packages/cli/node_modules
            - packages/local-api/node_modules
            - packages/local-client/node_modules
    
parameters:
  cli:
    type: boolean
    default: false
  local-api:
    type: boolean
    default: false
  local-client:
    type: boolean
    default: false

# VS Code Extension Version: 1.0.0